"""drop items.source

Revision ID: f378b757ab54
Revises: aa3f28965c7d
Create Date: 2026-05-22 23:22:38.939917

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f378b757ab54"
down_revision: str | None = "aa3f28965c7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column(
            "source",
            sa.VARCHAR(),
            server_default="catalog",
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
